=== sashokbg/git-training-usecases/web/resources/exercise.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "learn-git-question",
  "title": "Question",
  "description": "A Learn-Git Question Schema",
  "type": "array",
  "items": {
    "properties": {
      "exercise_title": {
        "type": "string",
        "description": "The question title"
      },
      "exercise_description": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "A detailed description of the exercise. Each line is a paragraph."
      },
      "command_history": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "script": {
        "type": "string"
      },
      "hints": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "checks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "User friendly name of the evaluation"
            },
            "explanation": {
              "type": "array",
              "description": "A detailed explanation of the evaluation.",
              "items": {
                "type": "string"
              }
            },
            "command": {
              "description": "The shell command to run for the evaluation. The return code should be 0",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== sashokbg/git-training-usecases/web/resources/exercises.db.json
[
  {
    "exercise_title": "Abort a merge",
    "exercise_description": [
      "While working on a branch, I initiated a merge.",
      "I am presented with merge prompt screen, but now I wish to abort the operation."
    ],
    "command_history": [
      "git merge"
    ],
    "script": "abort_a_merge.sh",
    "hints": [
      "Read the instructions on the merge prompt screen carefully.",
      "What happens if you close the terminal window without any changes ?",
      "What happens if you delete the commit message ?"
    ],
    "checks": [
      {
        "name": "Check commit message",
        "explanation": ["Check that the user has closed the editor with the commit message prompt."],
        "command": "test $(ps aux | grep -c \".git/MERGE_MSG\") -lt 2"
      },
      {
        "name": "Check git history",
        "explanation": ["Check the git history for presence of git merge commits."],
        "command": "test -z \"$(git lg | grep \"Merge branch 'feat' - Git Master (HEAD -> main)\")\""
      }
    ]
  },
  {
    "exercise_title": "Accidental Merge",
    "exercise_description": [
      "I worked on a feature and I wanted to rebase my branch upon main,",
      "But instead I accidentally did a merge.",
      "I want to the merge and have a linear history."
    ],
    "command_history": [
      "git merge"
    ],
    "script": "accidental_merge.sh",
    "hints": [
      "Use 'git lg' to check the history of the commits.",
      "Be careful not to loose any files, or any commits",
      "Git reflog is a trap",
      "Try resetting your HEAD~1"
    ],
    "checks": [
      {
        "name": "Check git history",
        "explanation": ["Check the git history for presence of git merge commits."],
        "command": "test -z \"$(git lg | grep \"Merge branch\")\""
      },
      {
        "name": "Check files",
        "explanation": ["Check that are all files are present in the working tree."],
        "command": "for f in file1.txt file2.txt file3.txt; do [ -f \"$f\" ] || { echo \"Missing $f\"; exit 1; }; done\n"
      },
      {
        "name": "Check commits",
        "explanation": ["Check all three commits are present 'first', 'second' and 'third'"],
        "command": "test -n \"$(git log | grep 'third')\""
      }
    ]
  },
  {
    "exercise_title": "Rebase Conflict Resolution",
    "exercise_description": [
      "I edited the text1.txt file",
      "I want to rebase my feat branch onto main",
      "But another user edited the same file on main"
    ],
    "command_history": [
      "git rebase main"
    ],
    "script": "rebase_conflict.sh",
    "hints": [
      "When conflicts occur during rebase, git will pause and show you the conflicted files.",
      "Edit the conflicted files to resolve merge conflicts manually.",
      "After resolving conflicts, use 'git add' to mark files as resolved.",
      "Continue the rebase process with 'git rebase --continue'.",
      "If you want to abort the rebase, use 'git rebase --abort'."
    ],
    "checks": [
      {
        "name": "Check commit history",
        "explanation": ["After rebasing all commits should be present in the history"],
        "command": "for s in \"I too edited file1\" \"edited file1\"; do git log --pretty=%s | grep -Fxq \"$s\" || { echo \"Missing commit: $s\"; exit 1; }; done"
      },
      {
        "name": "Check file content",
        "explanation": ["The file content should contain both the text from the first and second commits"],
        "command": "grep -q 'first' file1.txt && grep -q 'second' file1.txt"
      }
    ]
  },
  {
    "exercise_title": "Accidental Commit of Sensitive Data",
    "exercise_description": [
      "I accidentally committed my password to the repo",
      "I want to completely remove any mention of my password from the history"
    ],
    "command_history": [
    ],
    "script": "accidentally_commited_password.sh",
    "hints": [
      "Use 'git lg' to view the commit history",
      "On what branches is it present ?",
      "How do you remove the commit from both local and remote branch ?",
      "How about the git objects ?",
      "git-filter-repo --sensitive-data-removal --replace-text password.txt --force",
      "git push --force --mirror origin"
    ],
    "checks": [
      {
        "name": "Check git history for password",
        "command": "test $(git rev-list --objects --all | awk '{print $1}' | xargs -n1 git cat-file -p | grep 'pa$$word' -c) -eq 0",
        "explanation": ["The user should have successfully removed the commit from the history. Check the git objects to ensure that password is no longer present in git's internals."]
      },
      {
        "name": "Check git history",
        "explanation": ["Make sure other commits are not lost"],
        "command": "git lg | grep -q \"some content - Git Master\""
      }
    ]
  },
  {
    "exercise_title": "Pulling From another Repository",
    "exercise_description": [
      "A colleague works on another repository that is not related to mine and have pushed a commit called 'other commit'.",
      "I want to get the content of their commit on my repo.",
      "I added the second repository as a remote and pulled",
      "And I receive the following error when trying merge: fatal: refusing to merge unrelated histories"
    ],
    "command_history": [
      "git remote add second $OTHER_REPO_URL",
      "git fetch second",
      "git merge second/main"
    ],
    "script": "cannot_merge_unreleated_history.sh",
    "hints": [
      "Next hint will reveal the solution",
      "Use git merge --allow-unrelated-histories"
    ],
    "checks": [
      {
        "name": "Check worktree files",
        "explanation": [
          "The worktree should contain a file called 'file_other.txt' from the other remote."
        ],
        "command": "test -f file_other.txt"
      },
      {
        "name": "Check git history",
        "explanation": [
          "The git history should contain a commit called 'other commit' from the other remote."
        ],
        "command": "git lg | grep -q \"other commit - Git Master\""
      }
    ]
  },
  {
    "exercise_title": "Ref Exists Error",
    "command_history": [
      "git branch feat/mine",
      "git push origin feat/mine"
    ],
    "exercise_description": [
      "I try to create a branch called \"feat/my_feat\"",
      "But when I try to push it to the remote, it results in an error",
      "! [remote rejected] feat/mine -> feat/mine (failed to update ref)"
    ],
    "script": "checkout_error_ref_exists.sh",
    "checks": [
      {
        "name": "Check the local branch has been pushed to remote.",
        "explanation": ["Verify that the user has successfully resolved the error and pushed the branch to the remote."],
        "command": "test $(git branch -a | grep remotes/origin -c) -eq 2"
      }
    ],
    "hints": [
      "Is your local up-to date ?",
      "Do a git fetch, and then git branch -a",
      "Is there anything unusual in the branch name that came from the remote ?",
      "Since git refs are stored as files in directory structure, having a ref called 'feat' will cause problems when we want to create a branch called 'feat/<name>'.",
      "One solution would be to rename your local branch to feature/mine"
    ]
  },
  {
    "exercise_title": "Clean a WIP Commit",
    "script": "clean_wip_commit.sh",
    "exercise_description": [
      "I worked on a feature",
      "And I had to quickly change a branch so I performed a \"WIP\" commit at one point.",
      "I want to clean this WIP commit before opening my merge request."
    ],
    "command_history": [
      "echo \"content\" > file3.txt",
      "git add .",
      "git commit -m \"WIP\"",

      "echo \"content\" > file4.txt",
      "git add .",
      "git commit -m \"third commit\""
    ],
    "hints": [
      "Be careful, git reset HEAD~2 is not a good idea.",
      "How about interactive rebase ?",
      "git rebase -i HEAD~3, then prefix the commit with s to squash it.",
      "Don't forget to push --force your branch."
    ],
    "checks": [
      {
        "name": "Check git history",
        "explanation": ["Check the git history for presence of the WIP commit."],
        "command": "test -z \"$(git lg | grep \"WIP\")\""
      },
      {
        "name": "Check worktree files",
        "explanation": ["Check that the file related to the WIP commit has not been lost."],
        "command": "test -f file3.txt"
      }
    ]
  }
]
